name: Check Lua Formatting
on:
  pull_request_target: # This triggers the action on pull requests from forks
    types: [opened, synchronize, reopened] # Specify the types of pull request events to trigger the action

jobs:
  stylua-check:
    name: Stylua Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Stylua Check
        uses: JohnnyMorganz/stylua-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # This token is automatically provided by GitHub
          version: latest
          args: --check .
