name: Test Neovim Package

on:
  pull_request: ~
  push: ~

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: MunifTanjim/setup-neovim-action@v1
      - run: |
          nvim --version
      - name: Install dependencies
        run: |
          sudo apt-get update; sudo apt-get install -y luarocks
          sudo luarocks install busted
      - name: Run tests
        run: |
          busted tests