name: Test Neovim Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Neovim
        uses: shunsambongi/setup-nvim@v1
        with:
          version: stable

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y luarocks
          luarocks install busted
          busted --version

      - name: Run tests
        run: |
          busted tests